DROP TABLE IF EXISTS Departments;
CREATE TABLE Departments (
    Dpt NVARCHAR (255) NOT NULL,
    PRIMARY KEY (Dpt ASC)
);

DROP TABLE IF EXISTS Employees;
CREATE TABLE Employees (
    Emp NVARCHAR (255) NOT NULL,
    Dpt NVARCHAR (255) NOT NULL,
    Salary INT		NOT NULL,
    PRIMARY KEY (Dpt,Emp ASC)
);

DROP TABLE IF EXISTS Contacts;
CREATE TABLE Contacts (
    Dpt NVARCHAR (255)		NOT NULL,
    Contact NVARCHAR (255) NOT NULL,
    Client INT			NOT NULL,
    PRIMARY KEY (Dpt,Contact ASC)
);

DROP TABLE IF EXISTS Tasks;
CREATE TABLE Tasks (
    Emp NVARCHAR (255) NOT NULL,
    Tsk NVARCHAR (255) NOT NULL,
    PRIMARY KEY (Tsk,Emp ASC)
);
