DROP TABLE IF EXISTS People;
CREATE TABLE People (
    Name NVARCHAR (255) NOT NULL,
    Age   INT           NOT NULL,
    PRIMARY KEY (Name,Age ASC)
);

DROP TABLE IF EXISTS Couples;
CREATE TABLE Couples (
    Her NVARCHAR (255) NOT NULL,
    Him NVARCHAR (255) NOT NULL,
    PRIMARY KEY (Her,Him ASC)
);